/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Cookie.Login */
        post: operations["auth_cookie_login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Cookie.Logout */
        post: operations["auth_cookie_logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheppard/prompts/{prompt_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Prompts */
        put: operations["prompts_sheppard_prompts__prompt_name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheppard/stop-alarm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stop Alarm */
        put: operations["stop_alarm_sheppard_stop_alarm_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheppard/start-alarm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Alarm */
        get: operations["start_alarm_sheppard_start_alarm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning/routines/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Routines
         * @description Get all routines for the current user.
         */
        get: operations["list_routines_planning_routines__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning/preview/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Today
         * @description Preview what today would look like if scheduled.
         */
        get: operations["preview_today_planning_preview_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning/tomorrow/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Tomorrow
         * @description Preview what tomorrow would look like if scheduled.
         */
        get: operations["preview_tomorrow_planning_tomorrow_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning/date/{date}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Date
         * @description Preview what a specific date would look like if scheduled.
         */
        get: operations["preview_date_planning_date__date__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning/schedule/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Schedule Today
         * @description Schedule today with tasks from routines.
         */
        put: operations["schedule_today_planning_schedule_today_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning/tomorrow/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Schedule Tomorrow
         * @description Schedule tomorrow with tasks from routines.
         */
        put: operations["schedule_tomorrow_planning_tomorrow_schedule_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning/date/{date}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Schedule Date
         * @description Schedule a specific date with tasks from routines.
         */
        put: operations["schedule_date_planning_date__date__schedule_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/set-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Password
         * @description Update password for the current user.
         */
        post: operations["set_password_auth_set_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Login */
        get: operations["google_login_google_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/google/callback/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Login Callback */
        get: operations["google_login_callback_google_callback_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar-entries/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today */
        get: operations["today_calendar_entries_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar-entries/today/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today */
        get: operations["today_calendar_entries_today__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subscriptions */
        get: operations["list_subscriptions_push_subscriptions__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Subscription */
        delete: operations["delete_subscription_push_subscriptions__subscription_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscribe/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe */
        post: operations["subscribe_push_subscribe__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/today/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Todays Tasks
         * @description Get all tasks for today.
         */
        get: operations["list_todays_tasks_tasks_today__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{date}/{_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Task Action
         * @description Record an action on a task.
         */
        post: operations["add_task_action_tasks__date____id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/today/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Context Today
         * @description Get the complete context for today.
         */
        get: operations["get_context_today_days_today_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/tomorrow/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Context Tomorrow
         * @description Get the complete context for tomorrow.
         */
        get: operations["get_context_tomorrow_days_tomorrow_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/{date}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Context
         * @description Get the complete context for a specific date.
         */
        get: operations["get_context_days__date__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/{date}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Day
         * @description Preview what a day would look like if scheduled.
         */
        get: operations["preview_day_days__date__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/today/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Schedule Today
         * @description Schedule today with tasks from routines.
         */
        put: operations["schedule_today_days_today_schedule_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/{date}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Schedule Day
         * @description Schedule a specific day with tasks from routines.
         */
        put: operations["schedule_day_days__date__schedule_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Day
         * @description Update a day's status or template.
         */
        patch: operations["update_day_days__date__patch"];
        trace?: never;
    };
    "/days/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Templates
         * @description Get all available day templates.
         */
        get: operations["get_templates_days_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Templates
         * @description Get all available day templates.
         */
        get: operations["get_templates_days_templates__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/day-templates/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Day Template
         * @description Get a single day template by ID.
         */
        get: operations["get_day_template_day_templates__uuid__get"];
        /**
         * Update Day Template
         * @description Update a day template.
         */
        put: operations["update_day_template_day_templates__uuid__put"];
        post?: never;
        /**
         * Delete Day Template
         * @description Delete a day template.
         */
        delete: operations["delete_day_template_day_templates__uuid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/day-templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Day Templates
         * @description List day templates with pagination.
         */
        get: operations["list_day_templates_day_templates__get"];
        put?: never;
        /**
         * Create Day Template
         * @description Create a new day template.
         */
        post: operations["create_day_template_day_templates__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/day-templates/{uuid}/routines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Day Template Routine
         * @description Attach a routine to a day template.
         */
        post: operations["add_day_template_routine_day_templates__uuid__routines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/day-templates/{uuid}/routines/{routine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Day Template Routine
         * @description Detach a routine from a day template.
         */
        delete: operations["remove_day_template_routine_day_templates__uuid__routines__routine_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-definitions/available/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Available Task Definitions
         * @description Get the curated list of available task definitions that users can import.
         *
         *     Returns:
         *         List of task definition dictionaries (without user_id)
         */
        get: operations["get_available_task_definitions_task_definitions_available__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-definitions/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Definition
         * @description Get a single task definition by ID.
         */
        get: operations["get_task_definition_task_definitions__uuid__get"];
        /**
         * Update Task Definition
         * @description Update a task definition.
         */
        put: operations["update_task_definition_task_definitions__uuid__put"];
        post?: never;
        /**
         * Delete Task Definition
         * @description Delete a task definition.
         */
        delete: operations["delete_task_definition_task_definitions__uuid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-definitions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Task Definitions
         * @description List task definitions with pagination.
         */
        get: operations["list_task_definitions_task_definitions__get"];
        put?: never;
        /**
         * Create Task Definition
         * @description Create a new task definition.
         */
        post: operations["create_task_definition_task_definitions__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-definitions/bulk/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Create Task Definitions
         * @description Bulk create task definitions.
         */
        post: operations["bulk_create_task_definitions_task_definitions_bulk__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routines/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Routine
         * @description Get a single routine by ID.
         */
        get: operations["get_routine_routines__uuid__get"];
        /**
         * Update Routine
         * @description Update an existing routine.
         */
        put: operations["update_routine_routines__uuid__put"];
        post?: never;
        /**
         * Delete Routine
         * @description Delete a routine.
         */
        delete: operations["delete_routine_routines__uuid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routines/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Routines
         * @description List routines with pagination.
         */
        get: operations["list_routines_routines__get"];
        put?: never;
        /**
         * Create Routine
         * @description Create a new routine.
         */
        post: operations["create_routine_routines__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routines/{uuid}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Routine Task
         * @description Attach a task definition to a routine.
         */
        post: operations["add_routine_task_routines__uuid__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routines/{uuid}/tasks/{task_definition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Routine Task
         * @description Update an attached routine task (name/schedule).
         */
        put: operations["update_routine_task_routines__uuid__tasks__task_definition_id__put"];
        post?: never;
        /**
         * Remove Routine Task
         * @description Detach a task definition from a routine.
         */
        delete: operations["remove_routine_task_routines__uuid__tasks__task_definition_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Calendar
         * @description Get a single calendar by ID.
         */
        get: operations["get_calendar_calendars__uuid__get"];
        /**
         * Update Calendar
         * @description Update a calendar.
         */
        put: operations["update_calendar_calendars__uuid__put"];
        post?: never;
        /**
         * Delete Calendar
         * @description Delete a calendar.
         */
        delete: operations["delete_calendar_calendars__uuid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Calendars
         * @description List calendars with pagination.
         */
        get: operations["list_calendars_calendars__get"];
        put?: never;
        /**
         * Create Calendar
         * @description Create a new calendar.
         */
        post: operations["create_calendar_calendars__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Action */
        Action: {
            type: components["schemas"]["ActionType"];
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * ActionSchema
         * @description API schema for Action value object.
         */
        ActionSchema: {
            /** Id */
            id?: string | null;
            type: components["schemas"]["ActionType"];
            /** Data */
            data?: {
                [key: string]: string;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "COMPLETE" | "DELETE" | "EDIT" | "NOTIFY" | "PAUSE" | "PUNT" | "RESUME" | "START" | "VIEW";
        /**
         * AlarmSchema
         * @description API schema for Alarm value object.
         */
        AlarmSchema: {
            /** Name */
            name: string;
            /**
             * Time
             * Format: time
             */
            time: string;
            type: components["schemas"]["AlarmType"];
            /** Description */
            description?: string | null;
            /** Triggered At */
            triggered_at?: string | null;
        };
        /**
         * AlarmType
         * @enum {string}
         */
        AlarmType: "GENTLE" | "FIRM" | "LOUD" | "SIREN";
        /** Body_auth_cookie_login_auth_login_post */
        Body_auth_cookie_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * CalendarCreateSchema
         * @description API schema for creating a Calendar entity.
         */
        CalendarCreateSchema: {
            /** Name */
            name: string;
            /**
             * Auth Token Id
             * Format: uuid
             */
            auth_token_id: string;
            /** Platform Id */
            platform_id: string;
            /** Platform */
            platform: string;
            /** Last Sync At */
            last_sync_at?: string | null;
        };
        /**
         * CalendarEntrySchema
         * @description API schema for CalendarEntry entity.
         */
        CalendarEntrySchema: {
            /** Id */
            id?: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /**
             * Calendar Id
             * Format: uuid
             */
            calendar_id: string;
            /** Platform Id */
            platform_id: string;
            /** Platform */
            platform: string;
            /** Status */
            status: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            frequency: components["schemas"]["TaskFrequency"];
            /** Ends At */
            ends_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Actions */
            actions?: components["schemas"]["ActionSchema"][];
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /**
         * CalendarSchema
         * @description API schema for Calendar entity.
         */
        CalendarSchema: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /**
             * Auth Token Id
             * Format: uuid
             */
            auth_token_id: string;
            /** Platform Id */
            platform_id: string;
            /** Platform */
            platform: string;
            /** Last Sync At */
            last_sync_at?: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * CalendarUpdateSchema
         * @description API schema for Calendar update requests.
         */
        CalendarUpdateSchema: {
            /** Name */
            name?: string | null;
            /** Auth Token Id */
            auth_token_id?: string | null;
            /** Last Sync At */
            last_sync_at?: string | null;
        };
        /**
         * DayContextSchema
         * @description API schema for DayContext value object.
         */
        DayContextSchema: {
            day: components["schemas"]["DaySchema"];
            /** Calendar Entries */
            calendar_entries?: components["schemas"]["CalendarEntrySchema"][];
            /** Tasks */
            tasks?: components["schemas"]["TaskSchema"][];
        };
        /**
         * DayOfWeek
         * @enum {integer}
         */
        DayOfWeek: 0 | 1 | 2 | 3 | 4 | 5 | 6;
        /**
         * DaySchema
         * @description API schema for Day entity.
         */
        DaySchema: {
            /** Id */
            id?: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            alarm?: components["schemas"]["AlarmSchema"] | null;
            status: components["schemas"]["DayStatus"];
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Tags */
            tags?: components["schemas"]["DayTag"][];
            template?: components["schemas"]["DayTemplateSchema"] | null;
        };
        /**
         * DayStatus
         * @enum {string}
         */
        DayStatus: "UNSCHEDULED" | "SCHEDULED" | "IN_PROGRESS" | "COMPLETE";
        /**
         * DayTag
         * @enum {string}
         */
        DayTag: "WEEKEND" | "VACATION" | "WORKDAY";
        /**
         * DayTemplateCreateSchema
         * @description API schema for creating a DayTemplate entity.
         */
        DayTemplateCreateSchema: {
            /** Slug */
            slug: string;
            alarm?: components["schemas"]["AlarmSchema"] | null;
            /** Icon */
            icon?: string | null;
            /** Routine Ids */
            routine_ids?: string[];
        };
        /**
         * DayTemplateRoutineCreateSchema
         * @description API schema for attaching a routine to a day template.
         */
        DayTemplateRoutineCreateSchema: {
            /**
             * Routine Id
             * Format: uuid
             */
            routine_id: string;
        };
        /**
         * DayTemplateSchema
         * @description API schema for DayTemplate entity.
         */
        DayTemplateSchema: {
            /** Id */
            id?: string | null;
            /** Slug */
            slug: string;
            alarm?: components["schemas"]["AlarmSchema"] | null;
            /** Icon */
            icon?: string | null;
            /** Routine Ids */
            routine_ids?: string[];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * DayTemplateUpdateSchema
         * @description API schema for DayTemplate update requests.
         */
        DayTemplateUpdateSchema: {
            /** Slug */
            slug?: string | null;
            alarm?: components["schemas"]["AlarmSchema"] | null;
            /** Icon */
            icon?: string | null;
            /** Routine Ids */
            routine_ids?: string[] | null;
        };
        /**
         * DayUpdateSchema
         * @description API schema for Day update requests.
         */
        DayUpdateSchema: {
            alarm?: components["schemas"]["AlarmSchema"] | null;
            status?: components["schemas"]["DayStatus"] | null;
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Tags */
            tags?: components["schemas"]["DayTag"][] | null;
            /** Template Id */
            template_id?: string | null;
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PagedQueryResponse */
        PagedQueryResponse_CalendarSchema_: {
            /** Items */
            items: components["schemas"]["CalendarSchema"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
        };
        /** PagedQueryResponse */
        PagedQueryResponse_DayTemplateSchema_: {
            /** Items */
            items: components["schemas"]["DayTemplateSchema"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
        };
        /** PagedQueryResponse */
        PagedQueryResponse_RoutineSchema_: {
            /** Items */
            items: components["schemas"]["RoutineSchema"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
        };
        /**
         * PushSubscriptionSchema
         * @description API schema for PushSubscription entity.
         */
        PushSubscriptionSchema: {
            /** Id */
            id?: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Device Name */
            device_name?: string | null;
            /** Endpoint */
            endpoint: string;
            /** P256Dh */
            p256dh: string;
            /** Auth */
            auth: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RoutineCreateSchema
         * @description API schema for creating a Routine entity.
         */
        RoutineCreateSchema: {
            /** Name */
            name: string;
            category: components["schemas"]["TaskCategory"];
            routine_schedule: components["schemas"]["RoutineSchedule"];
            /**
             * Description
             * @default
             */
            description: string;
            /** Tasks */
            tasks?: components["schemas"]["RoutineTask-Input"][];
        };
        /** RoutineSchedule */
        RoutineSchedule: {
            frequency: components["schemas"]["TaskFrequency"];
            /** Weekdays */
            weekdays?: components["schemas"]["DayOfWeek"][] | null;
            /** Day Number */
            day_number?: number | null;
        };
        /**
         * RoutineSchema
         * @description API schema for Routine entity.
         */
        RoutineSchema: {
            /** Id */
            id?: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            category: components["schemas"]["TaskCategory"];
            routine_schedule: components["schemas"]["RoutineSchedule"];
            /**
             * Description
             * @default
             */
            description: string;
            /** Tasks */
            tasks?: components["schemas"]["RoutineTask-Output"][];
        };
        /** RoutineTask */
        "RoutineTask-Input": {
            /**
             * Task Definition Id
             * Format: uuid
             */
            task_definition_id: string;
            /** Name */
            name?: string | null;
            schedule?: components["schemas"]["TaskSchedule"] | null;
        };
        /** RoutineTask */
        "RoutineTask-Output": {
            /**
             * Task Definition Id
             * Format: uuid
             */
            task_definition_id: string;
            /** Name */
            name?: string | null;
            schedule?: components["schemas"]["TaskSchedule"] | null;
        };
        /**
         * RoutineTaskCreateSchema
         * @description API schema for attaching a RoutineTask.
         */
        RoutineTaskCreateSchema: {
            /**
             * Task Definition Id
             * Format: uuid
             */
            task_definition_id: string;
            /** Name */
            name?: string | null;
            schedule?: components["schemas"]["TaskSchedule"] | null;
        };
        /**
         * RoutineTaskUpdateSchema
         * @description API schema for updating an attached RoutineTask.
         */
        RoutineTaskUpdateSchema: {
            /** Name */
            name?: string | null;
            schedule?: components["schemas"]["TaskSchedule"] | null;
        };
        /**
         * RoutineUpdateSchema
         * @description API schema for Routine update requests.
         */
        RoutineUpdateSchema: {
            /** Name */
            name?: string | null;
            category?: components["schemas"]["TaskCategory"] | null;
            routine_schedule?: components["schemas"]["RoutineSchedule"] | null;
            /** Description */
            description?: string | null;
            /** Tasks */
            tasks?: components["schemas"]["RoutineTask-Input"][] | null;
        };
        /** StatusResponse */
        StatusResponse: Record<string, never>;
        /** SubscriptionRequest */
        SubscriptionRequest: Record<string, never>;
        /**
         * TaskCategory
         * @enum {string}
         */
        TaskCategory: "HYGIENE" | "GROOMING" | "SLEEP" | "HEALTH" | "FITNESS" | "MEDICAL" | "NUTRITION" | "COOKING" | "HOUSE" | "CLEANING" | "MAINTENANCE" | "ORGANIZATION" | "WORK" | "MEETING" | "PROFESSIONAL" | "FAMILY" | "SOCIAL" | "RELATIONSHIP" | "SHOPPING" | "ERRAND" | "COMMUTE" | "TRAVEL" | "ENTERTAINMENT" | "HOBBY" | "RECREATION" | "EDUCATION" | "LEARNING" | "FINANCE" | "BILLS" | "TECHNOLOGY" | "DIGITAL" | "PET" | "PLANNING" | "ADMIN";
        /**
         * TaskDefinitionCreateSchema
         * @description API schema for creating a TaskDefinition entity.
         */
        TaskDefinitionCreateSchema: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            type: components["schemas"]["TaskType"];
        };
        /**
         * TaskDefinitionSchema
         * @description API schema for TaskDefinition entity.
         */
        TaskDefinitionSchema: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /** Description */
            description: string;
            type: components["schemas"]["TaskType"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * TaskDefinitionUpdateSchema
         * @description API schema for TaskDefinition update requests.
         */
        TaskDefinitionUpdateSchema: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            type?: components["schemas"]["TaskType"] | null;
        };
        /**
         * TaskFrequency
         * @enum {string}
         */
        TaskFrequency: "DAILY" | "CUSTOM_WEEKLY" | "WEEKLY" | "ONCE" | "YEARLY" | "MONTHLY" | "BI_WEEKLY" | "WORK_DAYS" | "WEEKENDS";
        /** TaskSchedule */
        TaskSchedule: {
            /** Available Time */
            available_time?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            timing_type: components["schemas"]["TimingType"];
        };
        /**
         * TaskScheduleSchema
         * @description API schema for TaskSchedule value object.
         */
        TaskScheduleSchema: {
            /** Available Time */
            available_time?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            timing_type: components["schemas"]["TimingType"];
        };
        /**
         * TaskSchema
         * @description API schema for Task entity.
         */
        TaskSchema: {
            /** Id */
            id?: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            /** Name */
            name: string;
            status: components["schemas"]["TaskStatus"];
            task_definition: components["schemas"]["TaskDefinitionSchema"];
            category: components["schemas"]["TaskCategory"];
            frequency: components["schemas"]["TaskFrequency"];
            /** Completed At */
            completed_at?: string | null;
            schedule?: components["schemas"]["TaskScheduleSchema"] | null;
            /** Routine Id */
            routine_id?: string | null;
            /** Tags */
            tags?: components["schemas"]["TaskTag"][];
            /** Actions */
            actions?: components["schemas"]["ActionSchema"][];
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "COMPLETE" | "NOT_READY" | "READY" | "PUNT" | "NOT_STARTED" | "PENDING";
        /**
         * TaskTag
         * @enum {string}
         */
        TaskTag: "AVOIDANT" | "FORGETTABLE" | "IMPORTANT" | "URGENT" | "FUN";
        /**
         * TaskType
         * @enum {string}
         */
        TaskType: "MEAL" | "WORK" | "MEETING" | "EXERCISE" | "EVENT" | "SOCIAL" | "CHORE" | "ERRAND" | "SHOPPING" | "PERSONAL_CARE" | "ACTIVITY" | "ENTERTAINMENT" | "LEARNING" | "COMMUTE" | "TRAVEL" | "APPOINTMENT" | "COMMUNICATION" | "FINANCIAL" | "MAINTENANCE" | "PLANNING" | "TECHNOLOGY";
        /**
         * TimingType
         * @enum {string}
         */
        TimingType: "DEADLINE" | "FIXED_TIME" | "TIME_WINDOW" | "FLEXIBLE";
        /** UpdatePasswordRequest */
        UpdatePasswordRequest: Record<string, never>;
        /**
         * UserCreate
         * @description Schema for creating a new user.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean | null;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean | null;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean | null;
        };
        /**
         * UserRead
         * @description Schema for reading user data.
         */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            /** Phone Number */
            phone_number?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_cookie_login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_cookie_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_cookie_logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prompts_sheppard_prompts__prompt_name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_alarm_sheppard_stop_alarm_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    start_alarm_sheppard_start_alarm_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_routines_planning_routines__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineSchema"][];
                };
            };
        };
    };
    preview_today_planning_preview_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayContextSchema"];
                };
            };
        };
    };
    preview_tomorrow_planning_tomorrow_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayContextSchema"];
                };
            };
        };
    };
    preview_date_planning_date__date__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayContextSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_today_planning_schedule_today_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayContextSchema"];
                };
            };
        };
    };
    schedule_tomorrow_planning_tomorrow_schedule_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayContextSchema"];
                };
            };
        };
    };
    schedule_date_planning_date__date__schedule_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayContextSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_password_auth_set_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_login_google_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_login_callback_google_callback_login_get: {
        parameters: {
            query: {
                state: string;
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    today_calendar_entries_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEntrySchema"][];
                };
            };
        };
    };
    today_calendar_entries_today__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEntrySchema"][];
                };
            };
        };
    };
    list_subscriptions_push_subscriptions__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionSchema"][];
                };
            };
        };
    };
    delete_subscription_push_subscriptions__subscription_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscribe_push_subscribe__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_todays_tasks_tasks_today__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSchema"][];
                };
            };
        };
    };
    add_task_action_tasks__date____id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                _id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Action"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_context_today_days_today_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayContextSchema"];
                };
            };
        };
    };
    get_context_tomorrow_days_tomorrow_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayContextSchema"];
                };
            };
        };
    };
    get_context_days__date__context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayContextSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_day_days__date__preview_get: {
        parameters: {
            query?: {
                template_id?: string | null;
            };
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayContextSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_today_days_today_schedule_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayContextSchema"];
                };
            };
        };
    };
    schedule_day_days__date__schedule_put: {
        parameters: {
            query?: {
                template_id?: string | null;
            };
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayContextSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_day_days__date__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_templates_days_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayTemplateSchema"][];
                };
            };
        };
    };
    get_templates_days_templates__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayTemplateSchema"][];
                };
            };
        };
    };
    get_day_template_day_templates__uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayTemplateSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_day_template_day_templates__uuid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayTemplateUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayTemplateSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_day_template_day_templates__uuid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_day_templates_day_templates__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedQueryResponse_DayTemplateSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_day_template_day_templates__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayTemplateCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayTemplateSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_day_template_routine_day_templates__uuid__routines_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayTemplateRoutineCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayTemplateSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_day_template_routine_day_templates__uuid__routines__routine_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayTemplateSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_available_task_definitions_task_definitions_available__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_task_definition_task_definitions__uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDefinitionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_definition_task_definitions__uuid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskDefinitionUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDefinitionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_definition_task_definitions__uuid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_task_definitions_task_definitions__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDefinitionSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_definition_task_definitions__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskDefinitionCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDefinitionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_create_task_definitions_task_definitions_bulk__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                }[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDefinitionSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_routine_routines__uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_routine_routines__uuid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_routine_routines__uuid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_routines_routines__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedQueryResponse_RoutineSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_routine_routines__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_routine_task_routines__uuid__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineTaskCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_routine_task_routines__uuid__tasks__task_definition_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
                task_definition_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineTaskUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_routine_task_routines__uuid__tasks__task_definition_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
                task_definition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_calendars__uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_calendar_calendars__uuid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_calendar_calendars__uuid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calendars_calendars__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedQueryResponse_CalendarSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_calendar_calendars__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
