/**
 * Type constants extracted from auto-generated API types.
 * These arrays contain all possible values for each enum type.
 * 
 * IMPORTANT: This file is auto-generated by generate_ts_types.py
 * Do not modify manually - it will be overwritten when types are regenerated.
 * 
 * The types are extracted from the generated OpenAPI schema to ensure compatibility
 * with the types used throughout the application.
 */

import type { components } from "./api.generated";

// Extract the schema types from the generated OpenAPI types
// These match the types used in forms and throughout the app
type TaskType = components["schemas"]["TaskType"];
type TaskCategory = components["schemas"]["TaskCategory"];
type TaskFrequency = components["schemas"]["TaskFrequency"];

/**
 * All possible TaskType values from the auto-generated types
 * Source: components["schemas"]["TaskType"] in api.generated.ts
 */
export const ALL_TASK_TYPES: TaskType[] = [
  "MEAL",
  "WORK",
  "MEETING",
  "EXERCISE",
  "EVENT",
  "SOCIAL",
  "CHORE",
  "ERRAND",
  "SHOPPING",
  "PERSONAL_CARE",
  "ACTIVITY",
  "ENTERTAINMENT",
  "LEARNING",
  "COMMUTE",
  "TRAVEL",
  "APPOINTMENT",
  "COMMUNICATION",
  "FINANCIAL",
  "MAINTENANCE",
  "PLANNING",
  "TECHNOLOGY"
];

/**
 * All possible TaskCategory values from the auto-generated types
 * Source: components["schemas"]["TaskCategory"] in api.generated.ts
 */
export const ALL_TASK_CATEGORIES: TaskCategory[] = [
  "HYGIENE",
  "GROOMING",
  "SLEEP",
  "HEALTH",
  "FITNESS",
  "MEDICAL",
  "NUTRITION",
  "COOKING",
  "HOUSE",
  "CLEANING",
  "MAINTENANCE",
  "ORGANIZATION",
  "WORK",
  "MEETING",
  "PROFESSIONAL",
  "FAMILY",
  "SOCIAL",
  "RELATIONSHIP",
  "SHOPPING",
  "ERRAND",
  "COMMUTE",
  "TRAVEL",
  "ENTERTAINMENT",
  "HOBBY",
  "RECREATION",
  "EDUCATION",
  "LEARNING",
  "FINANCE",
  "BILLS",
  "TECHNOLOGY",
  "DIGITAL",
  "PET",
  "PLANNING",
  "ADMIN"
];

/**
 * All possible TaskFrequency values from the auto-generated types
 * Source: components["schemas"]["TaskFrequency"] in api.generated.ts
 */
export const ALL_TASK_FREQUENCIES: TaskFrequency[] = [
  "DAILY",
  "CUSTOM_WEEKLY",
  "WEEKLY",
  "ONCE",
  "YEARLY",
  "MONTHLY",
  "BI_WEEKLY",
  "WORK_DAYS",
  "WEEKENDS"
];
