/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
            type: components["schemas"]["ActionType"];
            /** Data */
            data?: {
                [key: string]: unknown;
            };

            type: components["schemas"]["AlarmType"];
            /** Description */
            description?: string | null;
            /** Triggered At */
            triggered_at?: string | null;

            status: components["schemas"]["DayStatus"];
            /** Scheduled At */
            scheduled_at?: string | null;

            messages?: components["schemas"]["Message"][];
        };

            alarm?: components["schemas"]["Alarm"] | null;
            /** Icon */
            icon?: string | null;

            alarm?: components["schemas"]["Alarm"] | null;
            /** Icon */
            icon?: string | null;

            actions?: components["schemas"]["Action"][];
            /**
             * Date
             * Format: date
             * @description Get the date for this event.
             */
            readonly date: string;

            detail?: components["schemas"]["ValidationError"][];
        };

            tasks?: components["schemas"]["RoutineTask"][];
        };

            weekdays?: components["schemas"]["DayOfWeek"][] | null;
        };

            schedule?: components["schemas"]["TaskSchedule"] | null;
        };

            keys: components["schemas"]["Keys"];
        };

            actions?: components["schemas"]["Action"][];
            /**
             * Date
             * Format: date
             * @description Get the date for this entity.
             *
             *     If _get_date() is implemented, it takes precedence.
             *     Otherwise, uses _get_datetime() with the configured timezone.
             */
            readonly date: string;

            type: components["schemas"]["TaskType"];
        };

            timing_type: components["schemas"]["TimingType"];
        };

            status?: components["schemas"]["DayStatus"] | null;
            /** Template Id */
            template_id?: string | null;
