"""Generate TypeScript types from OpenAPI schema file."""

import json
import subprocess
import sys
from pathlib import Path


def extract_enum_values(schema: dict, enum_name: str) -> list[str]:
    """Extract enum values from OpenAPI schema."""
    schemas = schema.get("components", {}).get("schemas", {})
    enum_schema = schemas.get(enum_name)

    if not enum_schema:
        raise ValueError(f"Enum {enum_name} not found in schema")

    enum_values = enum_schema.get("enum")
    if not enum_values:
        raise ValueError(f"Enum {enum_name} has no enum values")

    return enum_values


def generate_constants_file(
    output_file: Path,
    task_types: list[str],
    task_categories: list[str],
    task_frequencies: list[str],
) -> None:
    """Generate the constants.ts file with enum values."""
    content = f"""/**
 * Type constants extracted from auto-generated API types.
 * These arrays contain all possible values for each enum type.
 * 
 * IMPORTANT: This file is auto-generated by generate_ts_types.py
 * Do not modify manually - it will be overwritten when types are regenerated.
 * 
 * The types are extracted from the generated OpenAPI schema to ensure compatibility
 * with the types used throughout the application.
 */

import type {{ components }} from "./api.generated";

// Extract the schema types from the generated OpenAPI types
// These match the types used in forms and throughout the app
type TaskType = components["schemas"]["TaskType"];
type TaskCategory = components["schemas"]["TaskCategory"];
type TaskFrequency = components["schemas"]["TaskFrequency"];

/**
 * All possible TaskType values from the auto-generated types
 * Source: components["schemas"]["TaskType"] in api.generated.ts
 */
export const ALL_TASK_TYPES: TaskType[] = [
{chr(10).join(f'  "{value}",' if i < len(task_types) - 1 else f'  "{value}"' for i, value in enumerate(task_types))}
];

/**
 * All possible TaskCategory values from the auto-generated types
 * Source: components["schemas"]["TaskCategory"] in api.generated.ts
 */
export const ALL_TASK_CATEGORIES: TaskCategory[] = [
{chr(10).join(f'  "{value}",' if i < len(task_categories) - 1 else f'  "{value}"' for i, value in enumerate(task_categories))}
];

/**
 * All possible TaskFrequency values from the auto-generated types
 * Source: components["schemas"]["TaskFrequency"] in api.generated.ts
 */
export const ALL_TASK_FREQUENCIES: TaskFrequency[] = [
{chr(10).join(f'  "{value}",' if i < len(task_frequencies) - 1 else f'  "{value}"' for i, value in enumerate(task_frequencies))}
];
"""

    output_file.write_text(content, encoding="utf-8")


def main():
    """Generate TypeScript types from openapi.json schema file."""
    backend_dir = Path(__file__).parent.parent
    frontend_dir = backend_dir.parent / "frontend"
    schema_file = backend_dir / "openapi.json"

    if not schema_file.exists():
        print(f"Error: {schema_file} not found. Run export_openapi_schema.py first.")
        sys.exit(1)

    output_dir = frontend_dir / "src" / "types" / "api"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate types using openapi-typescript
    # Output directly to the final location as a single file
    output_file = output_dir / "api.generated.ts"

    try:
        subprocess.run(
            [
                "npx",
                "openapi-typescript",
                str(schema_file),
                "-o",
                str(output_file),
            ],
            cwd=str(frontend_dir),
            check=True,
        )

        print(f"Types generated in {output_file}")
    except subprocess.CalledProcessError as e:
        print(f"Error generating types: {e}")
        sys.exit(1)

    # Load the OpenAPI schema to extract enum values
    try:
        with open(schema_file, encoding="utf-8") as f:
            schema = json.load(f)
    except Exception as e:
        print(f"Error loading schema file: {e}")
        sys.exit(1)

    # Extract enum values
    try:
        task_types = extract_enum_values(schema, "TaskType")
        task_categories = extract_enum_values(schema, "TaskCategory")
        task_frequencies = extract_enum_values(schema, "TaskFrequency")
    except Exception as e:
        print(f"Error extracting enum values: {e}")
        sys.exit(1)

    # Generate constants file
    constants_file = output_dir / "constants.ts"
    try:
        generate_constants_file(
            constants_file,
            task_types,
            task_categories,
            task_frequencies,
        )
        print(f"Constants generated in {constants_file}")
    except Exception as e:
        print(f"Error generating constants file: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
