"""add alarms

Revision ID: 1672ca009d1f
Revises: f40a20e4fc51
Create Date: 2026-01-26 14:14:14.881060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1672ca009d1f'
down_revision: Union[str, Sequence[str], None] = 'f40a20e4fc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_templates', sa.Column('alarms', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('days', sa.Column('alarms', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'alarms')
    op.drop_column('day_templates', 'alarms')
    # ### end Alembic commands ###
