"""make calendars.auth_token_id optional

Revision ID: 1f724d18d193
Revises: a59be9cebd7a
Create Date: 2026-02-09 20:13:52.440823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '1f724d18d193'
down_revision: Union[str, Sequence[str], None] = 'a59be9cebd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendars', 'auth_token_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendars', 'auth_token_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
