"""add high level plan to days

Revision ID: 2533290d0732
Revises: 9df146a0b39f
Create Date: 2026-01-18 19:35:27.784173

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2533290d0732"
down_revision: str | Sequence[str] | None = "9df146a0b39f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "day_templates",
        sa.Column("high_level_plan_title", sa.String(), nullable=True),
    )
    op.add_column(
        "day_templates",
        sa.Column("high_level_plan_text", sa.Text(), nullable=True),
    )
    op.add_column(
        "days",
        sa.Column("high_level_plan_title", sa.String(), nullable=True),
    )
    op.add_column(
        "days",
        sa.Column("high_level_plan_text", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("days", "high_level_plan_text")
    op.drop_column("days", "high_level_plan_title")
    op.drop_column("day_templates", "high_level_plan_text")
    op.drop_column("day_templates", "high_level_plan_title")
    # ### end Alembic commands ###
