"""add attendance_status to events

Revision ID: 2699bc117edc
Revises: 1672ca009d1f
Create Date: 2026-01-27 20:48:24.148130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '2699bc117edc'
down_revision: Union[str, Sequence[str], None] = '1672ca009d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_entries', sa.Column('attendance_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_entries', 'attendance_status')
    # ### end Alembic commands ###
