"""add routines table

Revision ID: 2f301b2113eb
Revises: 31e780d37201
Create Date: 2026-01-24 15:23:28.654806

"""
from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2f301b2113eb'
down_revision: str | Sequence[str] | None = '31e780d37201'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('routine_definition_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('time_window', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_routines_date', 'routines', ['date'], unique=False)
    op.create_index('idx_routines_routine_definition_id', 'routines', ['routine_definition_id'], unique=False)
    op.create_index('idx_routines_user_id', 'routines', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_routines_user_id', table_name='routines')
    op.drop_index('idx_routines_routine_definition_id', table_name='routines')
    op.drop_index('idx_routines_date', table_name='routines')
    op.drop_table('routines')
    # ### end Alembic commands ###
