"""rename routines to routine_definitions

Revision ID: 31e780d37201
Revises: abdf45926ebe
Create Date: 2026-01-24 11:55:20.068310

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31e780d37201"
down_revision: str | Sequence[str] | None = "abdf45926ebe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("routines", "routine_definitions")
    op.alter_column(
        "routine_definitions",
        "routine_schedule",
        new_column_name="routine_definition_schedule",
    )
    op.drop_index(op.f("idx_routines_user_id"), table_name="routine_definitions")
    op.create_index(
        "idx_routine_definitions_user_id",
        "routine_definitions",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "day_templates",
        "routine_ids",
        new_column_name="routine_definition_ids",
    )
    op.drop_index(op.f("idx_tasks_routine_id"), table_name="tasks")
    op.alter_column(
        "tasks",
        "routine_id",
        new_column_name="routine_definition_id",
    )
    op.create_index(
        "idx_tasks_routine_definition_id",
        "tasks",
        ["routine_definition_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tasks_routine_definition_id", table_name="tasks")
    op.alter_column(
        "tasks",
        "routine_definition_id",
        new_column_name="routine_id",
    )
    op.create_index(op.f("idx_tasks_routine_id"), "tasks", ["routine_id"], unique=False)
    op.alter_column(
        "day_templates",
        "routine_definition_ids",
        new_column_name="routine_ids",
    )
    op.drop_index("idx_routine_definitions_user_id", table_name="routine_definitions")
    op.create_index(
        op.f("idx_routines_user_id"), "routine_definitions", ["user_id"], unique=False
    )
    op.alter_column(
        "routine_definitions",
        "routine_definition_schedule",
        new_column_name="routine_schedule",
    )
    op.rename_table("routine_definitions", "routines")
    # ### end Alembic commands ###
