"""initial migration

Revision ID: 3865389fa926
Revises: 
Create Date: 2025-12-29 07:25:20.917697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3865389fa926'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_uri', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('client_secret', sa.Text(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_auth_tokens_user_uuid', 'auth_tokens', ['user_uuid'], unique=False)
    op.create_table('calendars',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('auth_token_id', sa.String(), nullable=False),
    sa.Column('platform_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_calendars_user_uuid', 'calendars', ['user_uuid'], unique=False)
    op.create_table('day_templates',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alarm', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_day_templates_user_uuid', 'day_templates', ['user_uuid'], unique=False)
    op.create_table('days',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alarm', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_days_date', 'days', ['date'], unique=False)
    op.create_index('idx_days_user_uuid', 'days', ['user_uuid'], unique=False)
    op.create_table('events',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calendar_id', sa.String(), nullable=False),
    sa.Column('platform_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('people', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_events_calendar_id', 'events', ['calendar_id'], unique=False)
    op.create_index('idx_events_date', 'events', ['date'], unique=False)
    op.create_index('idx_events_user_uuid', 'events', ['user_uuid'], unique=False)
    op.create_table('messages',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_messages_date', 'messages', ['date'], unique=False)
    op.create_index('idx_messages_user_uuid', 'messages', ['user_uuid'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_push_subscriptions_user_uuid', 'push_subscriptions', ['user_uuid'], unique=False)
    op.create_table('routines',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('routine_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_routines_user_uuid', 'routines', ['user_uuid'], unique=False)
    op.create_table('task_definitions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_task_definitions_user_uuid', 'task_definitions', ['user_uuid'], unique=False)
    op.create_table('tasks',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('task_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('routine_id', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_tasks_date', 'tasks', ['date'], unique=False)
    op.create_index('idx_tasks_routine_id', 'tasks', ['routine_id'], unique=False)
    op.create_index('idx_tasks_user_uuid', 'tasks', ['user_uuid'], unique=False)
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tasks_user_uuid', table_name='tasks')
    op.drop_index('idx_tasks_routine_id', table_name='tasks')
    op.drop_index('idx_tasks_date', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_task_definitions_user_uuid', table_name='task_definitions')
    op.drop_table('task_definitions')
    op.drop_index('idx_routines_user_uuid', table_name='routines')
    op.drop_table('routines')
    op.drop_index('idx_push_subscriptions_user_uuid', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('idx_messages_user_uuid', table_name='messages')
    op.drop_index('idx_messages_date', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_events_user_uuid', table_name='events')
    op.drop_index('idx_events_date', table_name='events')
    op.drop_index('idx_events_calendar_id', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_days_user_uuid', table_name='days')
    op.drop_index('idx_days_date', table_name='days')
    op.drop_table('days')
    op.drop_index('idx_day_templates_user_uuid', table_name='day_templates')
    op.drop_table('day_templates')
    op.drop_index('idx_calendars_user_uuid', table_name='calendars')
    op.drop_table('calendars')
    op.drop_index('idx_auth_tokens_user_uuid', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
