"""add time_window to routines

Revision ID: 3ceb62b762f2
Revises: f69371db53c1
Create Date: 2026-01-24 09:20:07.525385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ceb62b762f2'
down_revision: Union[str, Sequence[str], None] = 'f69371db53c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('time_window', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routines', 'time_window')
    # ### end Alembic commands ###
