"""Add CalendarEntrySeries

Revision ID: 4888354bcb32
Revises: c10b788fa533
Create Date: 2026-01-08 11:28:03.837232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4888354bcb32'
down_revision: Union[str, Sequence[str], None] = 'c10b788fa533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_entry_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('calendar_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('platform_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('event_category', sa.String(), nullable=True),
    sa.Column('recurrence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_entry_series_calendar_id', 'calendar_entry_series', ['calendar_id'], unique=False)
    op.create_index('idx_calendar_entry_series_platform_id', 'calendar_entry_series', ['platform_id'], unique=False)
    op.create_index('idx_calendar_entry_series_user_id', 'calendar_entry_series', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_calendar_entry_series_user_id', table_name='calendar_entry_series')
    op.drop_index('idx_calendar_entry_series_platform_id', table_name='calendar_entry_series')
    op.drop_index('idx_calendar_entry_series_calendar_id', table_name='calendar_entry_series')
    op.drop_table('calendar_entry_series')
    # ### end Alembic commands ###
