"""add user profiles

Revision ID: 4d7b828b1e1f
Revises: a59be9cebd7a
Create Date: 2026-02-05 10:17:00.041922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d7b828b1e1f'
down_revision: Union[str, Sequence[str], None] = 'a59be9cebd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferred_name', sa.String(), nullable=True),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('work_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_profiles_user_id', 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_profiles_user_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
