"""denormalize_template_onto_day

Revision ID: 4f090731c713
Revises: cba01d469215
Create Date: 2025-12-30 20:43:37.362211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f090731c713'
down_revision: Union[str, Sequence[str], None] = 'cba01d469215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('template', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('days', 'template_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('days', 'template')
    # ### end Alembic commands ###
