"""denormalize_task_type_and_description

Revision ID: 4f63125d861e
Revises: 670f7a89ff08
Create Date: 2026-01-11 10:37:33.918711

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f63125d861e"
down_revision: str | Sequence[str] | None = "670f7a89ff08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("type", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("description", sa.String(), nullable=True))
    op.drop_column("tasks", "task_definition")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "task_definition",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("tasks", "description")
    op.drop_column("tasks", "type")
    # ### end Alembic commands ###
