"""Add CalendarEntrySeries to CalendarEntry

Revision ID: 5064d5446083
Revises: 4888354bcb32
Create Date: 2026-01-08 11:31:05.465210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5064d5446083'
down_revision: Union[str, Sequence[str], None] = '4888354bcb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_entries', sa.Column('calendar_entry_series_id', sa.UUID(), nullable=True))
    op.create_index('idx_calendar_entries_series_id', 'calendar_entries', ['calendar_entry_series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_calendar_entries_series_id', table_name='calendar_entries')
    op.drop_column('calendar_entries', 'calendar_entry_series_id')
    # ### end Alembic commands ###
