"""Add CalendarEntrySeries to CalendarEntry

Revision ID: 5064d5446083
Revises: 4888354bcb32
Create Date: 2026-01-08 11:31:05.465210

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5064d5446083"
down_revision: str | Sequence[str] | None = "4888354bcb32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calendar_entries",
        sa.Column("calendar_entry_series_id", sa.UUID(), nullable=True),
    )
    op.create_index(
        "idx_calendar_entries_series_id",
        "calendar_entries",
        ["calendar_entry_series_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_calendar_entries_series_id", table_name="calendar_entries")
    op.drop_column("calendar_entries", "calendar_entry_series_id")
    # ### end Alembic commands ###
