"""high_level_plan column

Revision ID: 5af9d36b31dc
Revises: 3c2b6c8c2c7d
Create Date: 2026-01-19 07:54:43.058914

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5af9d36b31dc"
down_revision: str | Sequence[str] | None = "3c2b6c8c2c7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "day_templates",
        sa.Column(
            "high_level_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("day_templates", "high_level_plan_text")
    op.drop_column("day_templates", "high_level_plan_title")
    op.add_column(
        "days",
        sa.Column(
            "high_level_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("days", "high_level_plan_text")
    op.drop_column("days", "high_level_plan_title")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "days",
        sa.Column(
            "high_level_plan_title", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "days",
        sa.Column(
            "high_level_plan_text", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("days", "high_level_plan")
    op.add_column(
        "day_templates",
        sa.Column(
            "high_level_plan_title", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "day_templates",
        sa.Column(
            "high_level_plan_text", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("day_templates", "high_level_plan")
    # ### end Alembic commands ###
