"""Add TimeBlocks

Revision ID: 670f7a89ff08
Revises: 5064d5446083
Create Date: 2026-01-10 12:04:34.516080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '670f7a89ff08'
down_revision: Union[str, Sequence[str], None] = '5064d5446083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_block_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_time_block_definitions_user_id', 'time_block_definitions', ['user_id'], unique=False)
    op.add_column('day_templates', sa.Column('time_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('days', sa.Column('time_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('days', sa.Column('active_time_block_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'active_time_block_id')
    op.drop_column('days', 'time_blocks')
    op.drop_column('day_templates', 'time_blocks')
    op.drop_index('idx_time_block_definitions_user_id', table_name='time_block_definitions')
    op.drop_table('time_block_definitions')
    # ### end Alembic commands ###
