"""fix duplicate tables

Revision ID: 6a8324eaaf9c
Revises: 6fbd2010f419
Create Date: 2026-01-19 20:52:16.462004

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6a8324eaaf9c"
down_revision: str | Sequence[str] | None = "6fbd2010f419"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_notifications_message_hash"), table_name="notifications")
    op.drop_index(
        op.f("idx_notifications_message_hash_sent_at"), table_name="notifications"
    )
    op.drop_index(op.f("idx_notifications_sent_at"), table_name="notifications")
    op.drop_index(op.f("idx_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("idx_notifications_user_sent_at"), table_name="notifications")
    op.drop_table("notifications")
    op.add_column("push_notifications", sa.Column("message", sa.Text(), nullable=True))
    op.add_column(
        "push_notifications", sa.Column("priority", sa.String(), nullable=True)
    )
    op.add_column("push_notifications", sa.Column("reason", sa.Text(), nullable=True))
    op.add_column(
        "push_notifications",
        sa.Column(
            "day_context_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "push_notifications", sa.Column("message_hash", sa.String(), nullable=True)
    )
    op.add_column(
        "push_notifications", sa.Column("triggered_by", sa.String(), nullable=True)
    )
    op.add_column(
        "push_notifications", sa.Column("llm_provider", sa.String(), nullable=True)
    )
    op.create_index(
        "idx_push_notifications_message_hash",
        "push_notifications",
        ["message_hash"],
        unique=False,
    )
    op.create_index(
        "idx_push_notifications_message_hash_sent_at",
        "push_notifications",
        ["message_hash", "sent_at"],
        unique=False,
    )
    op.create_index(
        "idx_push_notifications_user_sent_at",
        "push_notifications",
        ["user_id", "sent_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_push_notifications_user_sent_at", table_name="push_notifications"
    )
    op.drop_index(
        "idx_push_notifications_message_hash_sent_at", table_name="push_notifications"
    )
    op.drop_index(
        "idx_push_notifications_message_hash", table_name="push_notifications"
    )
    op.drop_column("push_notifications", "llm_provider")
    op.drop_column("push_notifications", "triggered_by")
    op.drop_column("push_notifications", "message_hash")
    op.drop_column("push_notifications", "day_context_snapshot")
    op.drop_column("push_notifications", "reason")
    op.drop_column("push_notifications", "priority")
    op.drop_column("push_notifications", "message")
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("priority", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "day_context_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "sent_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("message_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("triggered_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("llm_provider", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("notifications_pkey")),
    )
    op.create_index(
        op.f("idx_notifications_user_sent_at"),
        "notifications",
        ["user_id", "sent_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_notifications_sent_at"), "notifications", ["sent_at"], unique=False
    )
    op.create_index(
        op.f("idx_notifications_message_hash_sent_at"),
        "notifications",
        ["message_hash", "sent_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_notifications_message_hash"),
        "notifications",
        ["message_hash"],
        unique=False,
    )
    # ### end Alembic commands ###
