"""add snoozing

Revision ID: 6f5d7b32258b
Revises: ad43aca11af8
Create Date: 2026-01-25 19:27:30.268751

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f5d7b32258b"
down_revision: str | Sequence[str] | None = "ad43aca11af8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("routines", sa.Column("status", sa.String(), nullable=False))
    op.add_column("routines", sa.Column("snoozed_until", sa.DateTime(), nullable=True))
    op.add_column("tasks", sa.Column("snoozed_until", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "snoozed_until")
    op.drop_column("routines", "snoozed_until")
    op.drop_column("routines", "status")
    # ### end Alembic commands ###
