"""add template parts/usecases

Revision ID: 6fbd2010f419
Revises: f0b7d2a1c3e4
Create Date: 2026-01-19 14:16:28.849657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6fbd2010f419'
down_revision: Union[str, Sequence[str], None] = 'f0b7d2a1c3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('templates', sa.Column('usecase', sa.String(), nullable=False))
    op.drop_index(op.f('idx_templates_user_key'), table_name='templates')
    op.create_index('idx_templates_user_usecase_key', 'templates', ['user_id', 'usecase', 'key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_templates_user_usecase_key', table_name='templates')
    op.create_index(op.f('idx_templates_user_key'), 'templates', ['user_id', 'key'], unique=True)
    op.drop_column('templates', 'usecase')
    op.alter_column('tasks', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
