"""remove conversations

Revision ID: 7406d4d6e8fe
Revises: a1b2c3d4e5f6
Create Date: 2026-01-31 13:17:53.092917

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7406d4d6e8fe"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent FKs/columns FIRST, then drop conversations last.

    # factoids.conversation_id -> conversations.id
    op.drop_index(op.f("idx_factoids_conversation_id"), table_name="factoids")
    op.drop_constraint(
        op.f("factoids_conversation_id_fkey"), "factoids", type_="foreignkey"
    )
    op.drop_column("factoids", "conversation_id")

    # messages: replace conversation_id with user_id (backfill from conversations.user_id)
    op.add_column("messages", sa.Column("user_id", sa.UUID(), nullable=True))
    op.execute(
        sa.text(
            """
            UPDATE messages AS m
            SET user_id = c.user_id
            FROM conversations AS c
            WHERE m.conversation_id = c.id
            """
        )
    )
    op.drop_index(op.f("idx_messages_conversation_created"), table_name="messages")
    op.drop_index(op.f("idx_messages_conversation_id"), table_name="messages")
    op.drop_constraint(
        op.f("messages_conversation_id_fkey"), "messages", type_="foreignkey"
    )
    op.create_foreign_key(None, "messages", "users", ["user_id"], ["id"])
    op.create_index(
        "idx_messages_user_created",
        "messages",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index("idx_messages_user_id", "messages", ["user_id"], unique=False)
    op.drop_column("messages", "conversation_id")
    op.alter_column("messages", "user_id", existing_type=sa.UUID(), nullable=False)

    # users default/sms conversation pointers -> conversations.id
    op.drop_constraint(
        op.f("users_sms_conversation_id_fkey"), "users", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("users_default_conversation_id_fkey"), "users", type_="foreignkey"
    )
    op.drop_column("users", "sms_conversation_id")
    op.drop_column("users", "default_conversation_id")

    # Finally, drop conversations table + indexes
    op.drop_index(
        op.f("idx_conversations_bot_personality_id"), table_name="conversations"
    )
    op.drop_index(op.f("idx_conversations_channel"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_status"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_user_id"), table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate conversations FIRST, then recreate dependent columns/FKs.
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("bot_personality_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("channel", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("llm_provider", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "last_message_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bot_personality_id"],
            ["bot_personalities.id"],
            name=op.f("conversations_bot_personality_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("conversations_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("conversations_pkey")),
    )
    op.create_index(
        op.f("idx_conversations_user_id"), "conversations", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_conversations_status"), "conversations", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_conversations_channel"), "conversations", ["channel"], unique=False
    )
    op.create_index(
        op.f("idx_conversations_bot_personality_id"),
        "conversations",
        ["bot_personality_id"],
        unique=False,
    )

    op.add_column(
        "users",
        sa.Column(
            "default_conversation_id", sa.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("sms_conversation_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("users_sms_conversation_id_fkey"),
        "users",
        "conversations",
        ["sms_conversation_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("users_default_conversation_id_fkey"),
        "users",
        "conversations",
        ["default_conversation_id"],
        ["id"],
    )

    op.add_column(
        "factoids",
        sa.Column("conversation_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("factoids_conversation_id_fkey"),
        "factoids",
        "conversations",
        ["conversation_id"],
        ["id"],
    )
    op.create_index(
        op.f("idx_factoids_conversation_id"),
        "factoids",
        ["conversation_id"],
        unique=False,
    )

    op.add_column(
        "messages",
        sa.Column("conversation_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_conversation_id_fkey"),
        "messages",
        "conversations",
        ["conversation_id"],
        ["id"],
    )
    op.drop_index("idx_messages_user_id", table_name="messages")
    op.drop_index("idx_messages_user_created", table_name="messages")
    op.create_index(
        op.f("idx_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_messages_conversation_created"),
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.drop_column("messages", "user_id")
    # ### end Alembic commands ###
