"""add_default_conversation_id_and_sms_conversation_id_to_users

Revision ID: 7706cb7b0cd6
Revises: fac59f92bae3
Create Date: 2026-01-11 20:53:32.394276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7706cb7b0cd6'
down_revision: Union[str, Sequence[str], None] = 'fac59f92bae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_conversation_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('sms_conversation_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'conversations', ['sms_conversation_id'], ['id'])
    op.create_foreign_key(None, 'users', 'conversations', ['default_conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'sms_conversation_id')
    op.drop_column('users', 'default_conversation_id')
    # ### end Alembic commands ###
