"""add information for push subscriptions

Revision ID: 7e9a6d1caf5d
Revises: d8480a003906
Create Date: 2026-01-06 22:27:29.034566

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e9a6d1caf5d"
down_revision: str | Sequence[str] | None = "d8480a003906"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calendars",
        sa.Column(
            "sync_subscription", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "calendars", sa.Column("sync_subscription_id", sa.String(), nullable=True)
    )
    op.create_index(
        "idx_calendars_sync_subscription_id",
        "calendars",
        ["sync_subscription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_calendars_sync_subscription_id", table_name="calendars")
    op.drop_column("calendars", "sync_subscription_id")
    op.drop_column("calendars", "sync_subscription")
    # ### end Alembic commands ###
