"""add ady_id and date mixins

Revision ID: 91d5391dc1ff
Revises: b1c2d3e4f5a6
Create Date: 2026-03-09 19:29:21.861105

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91d5391dc1ff"
down_revision: str | Sequence[str] | None = "b1c2d3e4f5a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brain_dumps", sa.Column("day_id", sa.UUID(), nullable=True))
    op.create_index("idx_brain_dumps_day_id", "brain_dumps", ["day_id"], unique=False)
    op.add_column("calendar_entries", sa.Column("day_id", sa.UUID(), nullable=True))
    op.create_index(
        "idx_calendar_entries_day_id", "calendar_entries", ["day_id"], unique=False
    )
    op.add_column("messages", sa.Column("date", sa.Date(), nullable=True))
    op.add_column("messages", sa.Column("day_id", sa.UUID(), nullable=True))
    op.create_index("idx_messages_date", "messages", ["date"], unique=False)
    op.create_index("idx_messages_day_id", "messages", ["day_id"], unique=False)
    op.add_column("push_notifications", sa.Column("date", sa.Date(), nullable=True))
    op.add_column("push_notifications", sa.Column("day_id", sa.UUID(), nullable=True))
    op.create_index(
        "idx_push_notifications_date", "push_notifications", ["date"], unique=False
    )
    op.create_index(
        "idx_push_notifications_day_id", "push_notifications", ["day_id"], unique=False
    )
    op.add_column("routines", sa.Column("day_id", sa.UUID(), nullable=True))
    op.create_index("idx_routines_day_id", "routines", ["day_id"], unique=False)
    op.add_column("tasks", sa.Column("day_id", sa.UUID(), nullable=True))
    op.create_index("idx_tasks_day_id", "tasks", ["day_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tasks_day_id", table_name="tasks")
    op.drop_column("tasks", "day_id")
    op.drop_index("idx_routines_day_id", table_name="routines")
    op.drop_column("routines", "day_id")
    op.drop_index("idx_push_notifications_day_id", table_name="push_notifications")
    op.drop_index("idx_push_notifications_date", table_name="push_notifications")
    op.drop_column("push_notifications", "day_id")
    op.drop_column("push_notifications", "date")
    op.drop_index("idx_messages_day_id", table_name="messages")
    op.drop_index("idx_messages_date", table_name="messages")
    op.drop_column("messages", "day_id")
    op.drop_column("messages", "date")
    op.drop_index("idx_calendar_entries_day_id", table_name="calendar_entries")
    op.drop_column("calendar_entries", "day_id")
    op.drop_index("idx_brain_dumps_day_id", table_name="brain_dumps")
    op.drop_column("brain_dumps", "day_id")
    # ### end Alembic commands ###
