"""User.status and optional email

Revision ID: 94fcecdf55ab
Revises: 3199f059616c
Create Date: 2026-01-06 20:56:15.210348

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94fcecdf55ab"
down_revision: str | Sequence[str] | None = "3199f059616c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("status", sa.String(), server_default="active", nullable=False),
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=320), nullable=True
    )
    op.create_unique_constraint(None, "users", ["phone_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=320), nullable=False
    )
    op.drop_column("users", "status")
    # ### end Alembic commands ###
