"""drop_audit_logs_table

Revision ID: 9a0bb64850fb
Revises: 1f724d18d193
Create Date: 2026-02-13 21:39:06.977185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a0bb64850fb'
down_revision: Union[str, Sequence[str], None] = '1f724d18d193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_audit_logs_activity_type'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_activity'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_date'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_occurred'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('idx_audit_logs_user_occurred'), 'audit_logs', ['user_id', 'occurred_at'], unique=False)
    op.create_index(op.f('idx_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_user_date'), 'audit_logs', ['user_id', 'date'], unique=False)
    op.create_index(op.f('idx_audit_logs_user_activity'), 'audit_logs', ['user_id', 'activity_type'], unique=False)
    op.create_index(op.f('idx_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_activity_type'), 'audit_logs', ['activity_type'], unique=False)
    # ### end Alembic commands ###
