"""add brain_dump

Revision ID: 9df146a0b39f
Revises: 29deeb87043a
Create Date: 2026-01-17 21:08:05.237568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9df146a0b39f'
down_revision: Union[str, Sequence[str], None] = '29deeb87043a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('brain_dump_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'brain_dump_items')
    # ### end Alembic commands ###
