"""add calendar provider info to calendarEntries

Revision ID: a59be9cebd7a
Revises: b4c151a48b70
Create Date: 2026-02-04 22:35:17.072429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a59be9cebd7a'
down_revision: Union[str, Sequence[str], None] = 'b4c151a48b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_entries', sa.Column('ical_uid', sa.String(), nullable=True))
    op.add_column('calendar_entries', sa.Column('original_starts_at', sa.DateTime(), nullable=True))
    op.add_column('calendar_entries', sa.Column('recurring_platform_id', sa.String(), nullable=True))
    op.create_index('idx_calendar_entries_ical_uid', 'calendar_entries', ['ical_uid'], unique=False)
    op.create_index('idx_calendar_entries_recurring_platform_id', 'calendar_entries', ['recurring_platform_id'], unique=False)
    op.add_column('calendar_entry_series', sa.Column('ical_uid', sa.String(), nullable=True))
    op.add_column('calendar_entry_series', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index('idx_calendar_entry_series_ical_uid', 'calendar_entry_series', ['ical_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_calendar_entry_series_ical_uid', table_name='calendar_entry_series')
    op.drop_column('calendar_entry_series', 'deleted_at')
    op.drop_column('calendar_entry_series', 'ical_uid')
    op.drop_index('idx_calendar_entries_recurring_platform_id', table_name='calendar_entries')
    op.drop_index('idx_calendar_entries_ical_uid', table_name='calendar_entries')
    op.drop_column('calendar_entries', 'recurring_platform_id')
    op.drop_column('calendar_entries', 'original_starts_at')
    op.drop_column('calendar_entries', 'ical_uid')
    # ### end Alembic commands ###
