"""make BrainDump's their own table

Revision ID: abdf45926ebe
Revises: 3ceb62b762f2
Create Date: 2026-01-24 10:41:09.007501

"""
from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'abdf45926ebe'
down_revision: str | Sequence[str] | None = '3ceb62b762f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brain_dump_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brain_dump_items_date', 'brain_dump_items', ['date'], unique=False)
    op.create_index('idx_brain_dump_items_user_id', 'brain_dump_items', ['user_id'], unique=False)
    op.drop_column('days', 'brain_dump_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('brain_dump_items', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('idx_brain_dump_items_user_id', table_name='brain_dump_items')
    op.drop_index('idx_brain_dump_items_date', table_name='brain_dump_items')
    op.drop_table('brain_dump_items')
    # ### end Alembic commands ###
