"""Add foriegn key constraints

Revision ID: ad43aca11af8
Revises: ef4fbd733438
Create Date: 2026-01-25 16:53:41.991346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ad43aca11af8'
down_revision: Union[str, Sequence[str], None] = 'ef4fbd733438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'auth_tokens', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bot_personalities', 'bot_personalities', ['base_bot_personality_id'], ['id'])
    op.create_foreign_key(None, 'bot_personalities', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'brain_dumps', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'calendar_entries', 'calendars', ['calendar_id'], ['id'])
    op.create_foreign_key(None, 'calendar_entries', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'calendar_entries', 'calendar_entry_series', ['calendar_entry_series_id'], ['id'])
    op.create_foreign_key(None, 'calendar_entry_series', 'calendars', ['calendar_id'], ['id'])
    op.create_foreign_key(None, 'calendar_entry_series', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'calendars', 'auth_tokens', ['auth_token_id'], ['id'])
    op.create_foreign_key(None, 'calendars', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'bot_personalities', ['bot_personality_id'], ['id'])
    op.create_foreign_key(None, 'day_templates', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'days', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'factoids', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'factoids', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'push_notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'push_subscriptions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'routine_definitions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'routines', 'routine_definitions', ['routine_definition_id'], ['id'])
    op.create_foreign_key(None, 'routines', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'task_definitions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'routine_definitions', ['routine_definition_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'time_block_definitions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'usecase_configs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usecase_configs', type_='foreignkey')
    op.drop_constraint(None, 'time_block_definitions', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'task_definitions', type_='foreignkey')
    op.drop_constraint(None, 'routines', type_='foreignkey')
    op.drop_constraint(None, 'routines', type_='foreignkey')
    op.drop_constraint(None, 'routine_definitions', type_='foreignkey')
    op.drop_constraint(None, 'push_subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'push_notifications', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'factoids', type_='foreignkey')
    op.drop_constraint(None, 'factoids', type_='foreignkey')
    op.drop_constraint(None, 'days', type_='foreignkey')
    op.drop_constraint(None, 'day_templates', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'calendars', type_='foreignkey')
    op.drop_constraint(None, 'calendars', type_='foreignkey')
    op.drop_constraint(None, 'calendar_entry_series', type_='foreignkey')
    op.drop_constraint(None, 'calendar_entry_series', type_='foreignkey')
    op.drop_constraint(None, 'calendar_entries', type_='foreignkey')
    op.drop_constraint(None, 'calendar_entries', type_='foreignkey')
    op.drop_constraint(None, 'calendar_entries', type_='foreignkey')
    op.drop_constraint(None, 'brain_dumps', type_='foreignkey')
    op.drop_constraint(None, 'bot_personalities', type_='foreignkey')
    op.drop_constraint(None, 'bot_personalities', type_='foreignkey')
    op.drop_constraint(None, 'auth_tokens', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    # ### end Alembic commands ###
