"""add referenced_entities to pushes

Revision ID: b4c151a48b70
Revises: ec5d4919d174
Create Date: 2026-02-01 23:11:23.605950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4c151a48b70'
down_revision: Union[str, Sequence[str], None] = 'ec5d4919d174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_notifications', sa.Column('referenced_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_notifications', 'referenced_entities')
    # ### end Alembic commands ###
