"""rename brain_dump_items to brain_dumps

Revision ID: bdee15247763
Revises: 2f301b2113eb
Create Date: 2026-01-24 20:27:28.341630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdee15247763'
down_revision: Union[str, Sequence[str], None] = '2f301b2113eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brain_dumps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brain_dumps_date', 'brain_dumps', ['date'], unique=False)
    op.create_index('idx_brain_dumps_user_id', 'brain_dumps', ['user_id'], unique=False)
    op.drop_index(op.f('idx_brain_dump_items_date'), table_name='brain_dump_items')
    op.drop_index(op.f('idx_brain_dump_items_user_id'), table_name='brain_dump_items')
    op.drop_table('brain_dump_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brain_dump_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('brain_dump_items_pkey'))
    )
    op.create_index(op.f('idx_brain_dump_items_user_id'), 'brain_dump_items', ['user_id'], unique=False)
    op.create_index(op.f('idx_brain_dump_items_date'), 'brain_dump_items', ['date'], unique=False)
    op.drop_index('idx_brain_dumps_user_id', table_name='brain_dumps')
    op.drop_index('idx_brain_dumps_date', table_name='brain_dumps')
    op.drop_table('brain_dumps')
    # ### end Alembic commands ###
