"""add date to AuditLog

Revision ID: becfd1b98073
Revises: f1849ad9161b
Create Date: 2026-01-15 10:37:11.962252

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "becfd1b98073"
down_revision: str | Sequence[str] | None = "f1849ad9161b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_logs", sa.Column("date", sa.Date(), nullable=False))
    op.create_index(
        "idx_audit_logs_user_date", "audit_logs", ["user_id", "date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_audit_logs_user_date", table_name="audit_logs")
    op.drop_column("audit_logs", "date")
    # ### end Alembic commands ###
