"""Add event_category

Revision ID: c10b788fa533
Revises: cd0d102c29a8
Create Date: 2026-01-08 11:18:07.395806

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c10b788fa533"
down_revision: str | Sequence[str] | None = "cd0d102c29a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("calendar_entries", sa.Column("category", sa.String(), nullable=True))
    op.add_column(
        "calendars", sa.Column("default_event_category", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calendars", "default_event_category")
    op.drop_column("calendar_entries", "category")
    # ### end Alembic commands ###
