"""Add event_category

Revision ID: c10b788fa533
Revises: cd0d102c29a8
Create Date: 2026-01-08 11:18:07.395806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'c10b788fa533'
down_revision: Union[str, Sequence[str], None] = 'cd0d102c29a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_entries', sa.Column('category', sa.String(), nullable=True))
    op.add_column('calendars', sa.Column('default_event_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendars', 'default_event_category')
    op.drop_column('calendar_entries', 'category')
    # ### end Alembic commands ###
