"""initial migration

Revision ID: c4b595ab89f0
Revises:
Create Date: 2025-12-31 21:44:05.498469

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4b595ab89f0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_uri", sa.Text(), nullable=True),
        sa.Column("client_id", sa.Text(), nullable=True),
        sa.Column("client_secret", sa.Text(), nullable=True),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_auth_tokens_user_id", "auth_tokens", ["user_id"], unique=False)
    op.create_table(
        "calendar_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("calendar_id", sa.UUID(), nullable=False),
        sa.Column("platform_id", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("frequency", sa.String(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("people", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_calendar_entries_calendar_id",
        "calendar_entries",
        ["calendar_id"],
        unique=False,
    )
    op.create_index(
        "idx_calendar_entries_date", "calendar_entries", ["date"], unique=False
    )
    op.create_index(
        "idx_calendar_entries_user_id", "calendar_entries", ["user_id"], unique=False
    )
    op.create_table(
        "calendars",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("auth_token_id", sa.UUID(), nullable=False),
        sa.Column("platform_id", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_calendars_user_id", "calendars", ["user_id"], unique=False)
    op.create_table(
        "day_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("alarm", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column(
            "routine_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_day_templates_user_id", "day_templates", ["user_id"], unique=False
    )
    op.create_index(
        "idx_day_templates_user_slug", "day_templates", ["user_id", "slug"], unique=True
    )
    op.create_table(
        "days",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("template", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("alarm", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_days_date", "days", ["date"], unique=False)
    op.create_index("idx_days_user_id", "days", ["user_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_messages_date", "messages", ["date"], unique=False)
    op.create_index("idx_messages_user_id", "messages", ["user_id"], unique=False)
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("device_name", sa.String(), nullable=True),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("p256dh", sa.String(), nullable=False),
        sa.Column("auth", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_push_subscriptions_user_id",
        "push_subscriptions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "routines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column(
            "routine_schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("tasks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_routines_user_id", "routines", ["user_id"], unique=False)
    op.create_table(
        "task_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_task_definitions_user_id", "task_definitions", ["user_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "task_definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("frequency", sa.String(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("routine_id", sa.UUID(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tasks_date", "tasks", ["date"], unique=False)
    op.create_index("idx_tasks_routine_id", "tasks", ["routine_id"], unique=False)
    op.create_index("idx_tasks_user_id", "tasks", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("idx_tasks_user_id", table_name="tasks")
    op.drop_index("idx_tasks_routine_id", table_name="tasks")
    op.drop_index("idx_tasks_date", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("idx_task_definitions_user_id", table_name="task_definitions")
    op.drop_table("task_definitions")
    op.drop_index("idx_routines_user_id", table_name="routines")
    op.drop_table("routines")
    op.drop_index("idx_push_subscriptions_user_id", table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    op.drop_index("idx_messages_user_id", table_name="messages")
    op.drop_index("idx_messages_date", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_days_user_id", table_name="days")
    op.drop_index("idx_days_date", table_name="days")
    op.drop_table("days")
    op.drop_index("idx_day_templates_user_slug", table_name="day_templates")
    op.drop_index("idx_day_templates_user_id", table_name="day_templates")
    op.drop_table("day_templates")
    op.drop_index("idx_calendars_user_id", table_name="calendars")
    op.drop_table("calendars")
    op.drop_index("idx_calendar_entries_user_id", table_name="calendar_entries")
    op.drop_index("idx_calendar_entries_date", table_name="calendar_entries")
    op.drop_index("idx_calendar_entries_calendar_id", table_name="calendar_entries")
    op.drop_table("calendar_entries")
    op.drop_index("idx_auth_tokens_user_id", table_name="auth_tokens")
    op.drop_table("auth_tokens")
    # ### end Alembic commands ###
