"""remove timezone from CalendarEntry

Revision ID: cd0d102c29a8
Revises: 7e9a6d1caf5d
Create Date: 2026-01-07 18:09:07.693873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'cd0d102c29a8'
down_revision: Union[str, Sequence[str], None] = '7e9a6d1caf5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
