"""add goals to days

Revision ID: e0a696a6fa12
Revises: becfd1b98073
Create Date: 2026-01-15 18:01:58.946982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0a696a6fa12'
down_revision: Union[str, Sequence[str], None] = 'becfd1b98073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'goals')
    # ### end Alembic commands ###
