"""make make date and day_id not null

Revision ID: eb7bd5ab25eb
Revises: 91d5391dc1ff
Create Date: 2026-03-09 21:45:29.349954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'eb7bd5ab25eb'
down_revision: Union[str, Sequence[str], None] = '91d5391dc1ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brain_dumps', 'day_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('calendar_entries', 'day_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('messages', 'day_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('push_notifications', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('push_notifications', 'day_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('routines', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('routines', 'day_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasks', 'day_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'day_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('routines', 'day_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('routines', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('push_notifications', 'day_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('push_notifications', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('messages', 'day_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('calendar_entries', 'day_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('brain_dumps', 'day_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
