"""add triggers and tactics

Revision ID: f40a20e4fc51
Revises: 6f5d7b32258b
Create Date: 2026-01-25 21:09:40.161565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f40a20e4fc51'
down_revision: Union[str, Sequence[str], None] = '6f5d7b32258b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tactics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tactics_user_id', 'tactics', ['user_id'], unique=False)
    op.create_table('triggers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_triggers_user_id', 'triggers', ['user_id'], unique=False)
    op.create_table('trigger_tactics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trigger_id', sa.UUID(), nullable=False),
    sa.Column('tactic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tactic_id'], ['tactics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trigger_id', 'tactic_id')
    )
    op.create_index('idx_trigger_tactics_tactic_id', 'trigger_tactics', ['tactic_id'], unique=False)
    op.create_index('idx_trigger_tactics_trigger_id', 'trigger_tactics', ['trigger_id'], unique=False)
    op.create_index('idx_trigger_tactics_user_id', 'trigger_tactics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trigger_tactics_user_id', table_name='trigger_tactics')
    op.drop_index('idx_trigger_tactics_trigger_id', table_name='trigger_tactics')
    op.drop_index('idx_trigger_tactics_tactic_id', table_name='trigger_tactics')
    op.drop_table('trigger_tactics')
    op.drop_index('idx_triggers_user_id', table_name='triggers')
    op.drop_table('triggers')
    op.drop_index('idx_tactics_user_id', table_name='tactics')
    op.drop_table('tactics')
    # ### end Alembic commands ###
