"""add_ai_chatbot_tables

Revision ID: fac59f92bae3
Revises: 4f63125d861e
Create Date: 2026-01-11 20:13:24.273144

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fac59f92bae3"
down_revision: str | Sequence[str] | None = "4f63125d861e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_personalities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_bot_personality_id", sa.UUID(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("user_amendments", sa.Text(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_bot_personalities_base_id",
        "bot_personalities",
        ["base_bot_personality_id"],
        unique=False,
    )
    op.create_index(
        "idx_bot_personalities_user_id", "bot_personalities", ["user_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bot_personality_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("llm_provider", sa.String(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_conversations_bot_personality_id",
        "conversations",
        ["bot_personality_id"],
        unique=False,
    )
    op.create_index(
        "idx_conversations_channel", "conversations", ["channel"], unique=False
    )
    op.create_index(
        "idx_conversations_status", "conversations", ["status"], unique=False
    )
    op.create_index(
        "idx_conversations_user_id", "conversations", ["user_id"], unique=False
    )
    op.create_table(
        "factoids",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("factoid_type", sa.String(), nullable=False),
        sa.Column("criticality", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column("ai_suggested", sa.String(), nullable=False),
        sa.Column("user_confirmed", sa.String(), nullable=False),
        sa.Column("last_accessed", sa.DateTime(), nullable=False),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_factoids_conversation_id", "factoids", ["conversation_id"], unique=False
    )
    op.create_index(
        "idx_factoids_criticality", "factoids", ["criticality"], unique=False
    )
    op.create_index(
        "idx_factoids_factoid_type", "factoids", ["factoid_type"], unique=False
    )
    op.create_index(
        "idx_factoids_user_criticality",
        "factoids",
        ["user_id", "criticality"],
        unique=False,
    )
    op.create_index("idx_factoids_user_id", "factoids", ["user_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_messages_conversation_id", "messages", ["conversation_id"], unique=False
    )
    op.create_index("idx_messages_created_at", "messages", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_messages_created_at", table_name="messages")
    op.drop_index("idx_messages_conversation_id", table_name="messages")
    op.drop_index("idx_messages_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_factoids_user_id", table_name="factoids")
    op.drop_index("idx_factoids_user_criticality", table_name="factoids")
    op.drop_index("idx_factoids_factoid_type", table_name="factoids")
    op.drop_index("idx_factoids_criticality", table_name="factoids")
    op.drop_index("idx_factoids_conversation_id", table_name="factoids")
    op.drop_table("factoids")
    op.drop_index("idx_conversations_user_id", table_name="conversations")
    op.drop_index("idx_conversations_status", table_name="conversations")
    op.drop_index("idx_conversations_channel", table_name="conversations")
    op.drop_index("idx_conversations_bot_personality_id", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("idx_bot_personalities_user_id", table_name="bot_personalities")
    op.drop_index("idx_bot_personalities_base_id", table_name="bot_personalities")
    op.drop_table("bot_personalities")
    # ### end Alembic commands ###
